# This is a basic workflow to help you get started with Actions
# downloads changeNotes.opml every 15 minutes http://drummer.scripting.com/davewiner/drummer/changeNotes.opml

name: ScriptingDrummerBackupsPlusMD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download Feed
      run: |-       
        curl "http://drummer.scripting.com/davewiner/drummer/changeNotes.opml" -o opml/changeNotes.opml
        curl http://scripting.com/rss.xml -o rss/scripting.com-rss.xml
    - name: pandoc conversion
      uses: docker://pandoc/core:2.9 
      with:
        args: >-  # allows you to break string into multiple lines
          --standalone
          --from=opml
          --to=gfm
          --output=opml/changeNotes.md
          opml/changeNotes.opml      
#    - name: sed on md file
#      run: >-
#          sed -e 's/^## /* /g' opml/changeNotes.md | 
#          sed -e 's/^### /    * /g' | 
#          sed -e 's/^#### /        * /g' | 
#          sed -e 's/^##### /            * /g' > opml/changeNotes.md
    - name: Commit and push changes
      run: |-
            git diff
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            #git diff-index --quiet HEAD -- || (git add -A && git commit -m "Updated with latest")
            [ ! -z "$(git status --porcelain=v1 2>/dev/null)" ] && (git add -A && git commit -m "Updated with latest")
            git push
